services:
  - type: web
    name: bhavya-delivery-api
    runtime: node
    plan: free
    root: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
